### PR TITLE
Improve the Upgrade section of the regolancer bonus guide

### PR DESCRIPTION
**Pull request by Bitcoinite**
Changed the upgrade command from a specific version to the latest one. This makes it easier for users to upgrade, since they don't need to check the exact version number of the latest release.

### CODE REVIEW

**Review by blckbx — COMMENTED** [review]
LGTM

for first time setup: do we want to use `latest` here as well? 
But then I guess we need to update the guide for the version check anyway.

**Review by blckbx — COMMENTED** [review]
utACK

**Review by twofaktor — CHANGES_REQUESTED** [review]
Line 65: `GOARCH=arm64 go install github.com/rkfg/regolancer@latest`

` For RPi run it as GOARCH=arm64 go install github.com/rkfg/regolancer@latest if you run a 64 bit system (and you should!)`

Ref: https://github.com/rkfg/regolancer#installation

what about an 'Autostart on boot'  section through regolancer.service file on systemd?

**Comment by satsHIVE** [comment]
This guide is in the making right now. ;)

**Comment by twofaktor** [comment]
Line 67: https://github.com/raspibolt/raspibolt/pull/1162/files#diff-2be0a3351d69f05b8f7c1a90a3592b0679ca82bff853936485457b67baa09758L67

Change to --> Note: Adjust the "regolancer@v1.9.0" part from the commands below to the actual version you have installed.

**Comment by satsHIVE** [comment]
> Line 67: https://github.com/raspibolt/raspibolt/pull/1162/files#diff-2be0a3351d69f05b8f7c1a90a3592b0679ca82bff853936485457b67baa09758L67
> 
> Change to --> Note: Adjust the "regolancer@v1.9.0" part from the commands below to the actual version you have installed.

I guess this should not be adjusted but rather removed. It no longer makes sense since started using "@latest".

**Comment by Bitcoinite** [comment]
> > Line 67: https://github.com/raspibolt/raspibolt/pull/1162/files#diff-2be0a3351d69f05b8f7c1a90a3592b0679ca82bff853936485457b67baa09758L67
> > Change to --> Note: Adjust the "regolancer@v1.9.0" part from the commands below to the actual version you have installed.
> 
> I guess this should not be adjusted but rather removed. It no longer makes sense since started using "@latest".

I removed the note altogether since we don't need it anymore.

**Review by twofaktor — APPROVED** [review]
LGTM! utACK

**Comment by Bitcoinite** [comment]
> One more nit: Line 80:
> 
> ```shell
> $ cp /home/regolancer/go/pkg/mod/github.com/rkfg/regolancer@v1.6.3/config.json.sample /home/regolancer/config.json
> ```
> 
> still references v1.6.3 instead of 1.9.0. After that it's gtg!

Done. Also added the note I just deleted from line 67, since we need a version number here.

**Review by blckbx — APPROVED** [review]
~~utACK~~
tACK amd64

**Pull request merged**
