### PR TITLE
shorten the menu separators on the website

### PR DESCRIPTION
**Pull request by aheinzer**
#### What

shorten the menu separators on the website

### Why

looks better on the website

#### How

shortened the separator lines from 26 to 20 chars

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [X] simple bug fix

Fixes raspibolt/raspibolt#1285

#### Test & maintenance

Did not know how to test this locally.

### CODE REVIEW

**Comment by Mynima** [comment]
I was wonder why this was but I guess it is due to screen display sizes?

No problem here:
image

Resized just before the menu auto moves to the dropdown in the top right:
image

I guess I don't have an issue with this update never really spotted the issue tbh.

LGTM.

**Review by Mynima — APPROVED** [review]
utACK

**Comment by aheinzer** [comment]
Even on a bigger screen the lines are broken because the width of the menu sees to be fixed and too small.
Here 2 screenshots, both on MacBook on a external monitor with 2560 x 1440 pixel, on Safari and Chrome.

Safari

Chrome

**Comment by Mynima** [comment]
> Even on a bigger screen the lines are broken because the width of the menu sees to be fixed and too small. Here 2 screenshots, both on MacBook on a external monitor with 2560 x 1440 pixel, on Safari and Chrome.

Yeah doesn't look ideal. Thanks for catching it and making the update. I've no issues with this, @blckbx see what you think.

**Comment by kristapsk** [comment]
I have this issue both with Firefox and Google Chrome under Linux, with 1920x1080 screen resolution, without this change, on current master.

image

image

**Comment by Mynima** [comment]
@kristapsk is it worth pushing this one through? It doesn't seem contentious and could resolve the issue for a few folks.

**Comment by kristapsk** [comment]
I'm not sure this is the right approach to fix this. Couldn't we use some CSS instead to just hide overflow, if it happens, instead of wrapping?

**Comment by Mynima** [comment]
> I'm not sure this is the right approach to fix this. Couldn't we use some CSS instead to just hide overflow, if it happens, instead of wrapping?

Ah yeah, it would be better to have a more robust approach to fixing this.

**Pull request closed without merging**
