### PR TITLE
[UPDATE] Bash completion

### PR DESCRIPTION
**Pull request by twofaktor**
#### What

Update bash completion to the latest changes and other improvements

#### Why

Keep the guide updated

#### How

- Updated download URLs to the new PATH
- Changed format to standardize with the rest of the guide
- Changed a command to improve the result

#### Scope

- [ ] significant change to core configuration
- [X] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Tested for me and working fine ✅

### CODE REVIEW

**Review by blckbx — APPROVED** [review]
tACK

**Comment by kristapsk** [comment]
Will test this in coming days.

**Review by kristapsk — APPROVED** [review]
ACK 7f1544f3f97673c00ad65856947e0cdb65b52f1c

**Comment by twofaktor** [comment]
OK, let's go to the master!

**Pull request merged**
