### PR TITLE
Bump Bitcoin Core from 26.0 to 26.1

### PR DESCRIPTION
**Pull request by kristapsk**
#### What

Update the Bitcoin Core guide to the latest release 26.1.

### Why

Keeping up with latest developments and improvements (see [release notes](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-26.1.md)).

#### Scope

- [X] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

### CODE REVIEW

**Comment by twofaktor** [comment]
> > @kristapsk could you reply to me?
> 
> Where?

I left a comment on the code

**Comment by kristapsk** [comment]
> > > @kristapsk could you reply to me?
> > 
> > 
> > Where?
> 
> I left a comment on the code
> 
> 

Your comment is "pending", that's why others don't see it.

**Comment by twofaktor** [comment]
> > > > @kristapsk could you reply to me?
> > > 
> > > 
> > > Where?
> > 
> > 
> > I left a comment on the code
> > 
> 
> Your comment is "pending", that's why others don't see it.

Ok, already you can see it

**Comment by blckbx** [comment]
LGTM

one proposed addition for `bitcoind.service` as seen in https://github.com/bitcoin/bitcoin/pull/28340 : 
```
# Restrict ABIs to help ensure MemoryDenyWriteExecute is enforced
SystemCallArchitectures=native
```

FWIW, we shouldn't hurry on 27.0. It currently breaks stuff in LND (`sendcoins`, `closechannel` and sweeping of a force close): https://github.com/lightningnetwork/lnd/issues/8571

**Comment by twofaktor** [comment]
> LGTM
> 
> one proposed addition for `bitcoind.service` as seen in https://github.com/bitcoin/bitcoin/pull/28340 : 
> ```
> # Restrict ABIs to help ensure MemoryDenyWriteExecute is enforced
> SystemCallArchitectures=native
> ```
> 
> FWIW, we shouldn't hurry on 27.0. It currently breaks stuff in LND (`sendcoins`, `closechannel` and sweeping of a force close): https://github.com/lightningnetwork/lnd/issues/8571

I saw on description:

bitcoind before v26.0
lnd sendcoins bcrt1qgy6djk4t4e3l6ldu29r4834zsye2dv9s2h8t5f 1000 succeed.

Does that mean it also happens with v26.1 same like v27?

**Comment by blckbx** [comment]
> Does that mean it also happens with v26.1 same as v27?

Without further diving into github/bitcoin, some noderunners reported ok running 26.1 and I just tested it manually. 26.1 still works fine.

**Comment by kristapsk** [comment]
I haven't noticed any issues with LND and Bitcoin Core v26.1, even opened a new channel after upgrade.

**Comment by twofaktor** [comment]
https://github.com/lightningnetwork/lnd/issues/8571#issuecomment-2065368921

https://github.com/lightningnetwork/lnd/pull/8664

**Comment by twofaktor** [comment]
https://github.com/lightningnetwork/lnd/releases/tag/v0.17.5-beta

**Review by blckbx — APPROVED** [review]
I don't quite recall the discussion of whether `bitcoin-cli --version` or `bitcoind --version` should be used. However tACK

**Comment by twofaktor** [comment]
Ignoring the debate `bitcoin-cli --version` vs `bitcoind --version`

Bitcoin Core v27 + LND v0.17.5 is now compatible, should we edit this PR to update to v27 directly?

**Comment by kristapsk** [comment]
> Ignoring the debate `bitcoin-cli --version` vs `bitcoind --version`
> 
> Bitcoin Core v27 + LND v0.17.5 is now compatible, should we edit this PR to update to v27 directly?

I would say no, let's create a new PR for that, as migrating to v27 needs more testing, RaspiBolt guides include not only LND, it could break compatibility with other software too.

**Review by twofaktor — APPROVED** [review]
tACK

**Pull request merged**
