### PR TITLE
Update RTL guide to v0.13.1 + use "--omit=dev" flag + a few formating bug fixes

### PR DESCRIPTION
**Pull request by VajraOfIndra**
#### What

* Update guide to latest version 0.13.1
* Replaces outadated `--only=dev` flag by recommended `--omit=dev`
* Fixes a few formatting bugs

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple bug fix

#### Test & maintenance

* Check that all locations referencing a version number have been updated
* Test that new flag `--omit=dev `is working

### CODE REVIEW

**Comment by twofaktor** [comment]
Add comment "# Hidden Service RTL" between 245-246 to standardize and clarify Tor hidden services according to the rest of the guide

References:
https://raspibolt.org/guide/raspberry-pi/privacy.html#ssh-server
https://raspibolt.org/guide/bonus/lightning/thunderhub.html#remote-access-over-tor-optional

**Comment by VajraOfIndra** [comment]
> # Hidden Service RTL

Done 👍

**Review by blckbx — APPROVED** [review]
tACK

**Comment by blckbx** [comment]
Needs a rebase, then gtg.

**Comment by VajraOfIndra** [comment]
> Needs a rebase, then gtg.

Done! Let's go to master.

**Pull request merged**
