### PR TITLE
Update "Odroid Setup Guide" for 64-bit and for RockPro64

### PR DESCRIPTION
**Pull request by PLK2**
#### What

Using the guide for my RockPro64 resulted in a few hang ups (detailed below).

### Why

Needs updating.

#### How

See below in Fixes.

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

Fixes #

https://raspibolt.org/bonus/raspberry-pi/odroid-setup.html#download-bitcoin-core

## 1. ARM64
For ARM 64, Bitcoin Core has a different filename structure from the 32-bit, which threw me off. 

https://bitcoincore.org/bin/bitcoin-core-22.0/bitcoin-22.0- **aarch64-linux-gnu.tar.gz**
vs.
https://bitcoincore.org/bin/bitcoin-core-22.0/bitcoin-22.0- **arm-linux-gnueabihf.tar.gz** (as shown in the Guide).

Users should be more explicitly directed to the Arm64 download.

## 2. Verifying download
"sha256sum --check SHA256SUMS.asc --ignore-missing" works for bitcoin-0.21.0 but does not appear to work for bitcoin-22.0. I get a "not properly formatted" error. I tried similar on MacOS and get similar errors. Seems something changed at Bitcoin Core and I'm not sure of what the fix is.

## 3. RockPro64
I was able to follow the guide and get everything running on my RockPro64 + microSD + NVMe/PCIe + Armbian_21.08.1_Rockpro64_buster_current_5.10.60. Suggest listing RockPro64 to the title of this Bonus Guide.

#### Test & maintenance

I can continue to provide updates as I build out my RockPro64.

### CODE REVIEW

**Comment by VajraOfIndra** [comment]
Thanks for the feedback @PLK2 !

There are 49 modified files in your PR right now, could you update your branch by fetching and merging all the latest commits? it should leave only one modified file (the odroid guide you modified) which will be easier to look at and review :)

**Comment by PLK2** [comment]
> Thanks for the feedback @PLK2 !
> 
> There are 49 modified files in your PR right now, could you update your branch by fetching and merging all the latest commits? it should leave only one modified file (the odroid guide you modified) which will be easier to look at and review :)

I am totally new at this. Reading the github "how to" guide right now...then I'll do that. ;)

**Comment by VajraOfIndra** [comment]
> I am totally new at this. Reading the github "how to" guide right now...then I'll do that. ;)

Great stuff! I'm quite new to this myself, but if you have any questions, don't hesitate to ask! :)

**Comment by VajraOfIndra** [comment]
> I am totally new at this. Reading the github "how to" guide right now...then I'll do that. ;)


In the root directory of your branch (the one where you added the updates you'd like to push), click on "Fetch upstream" and then "Fetch and merge". It will update your branch to match the present-day state of the RaspiBolt master branch (but will preserve your changes)

**Comment by PLK2** [comment]
I'm not seeing "Fetch upstream". See screenshot.
That option appears if I Fork the repository, though...
Screen Shot 2022-01-21 at 1 01 21 PM

**Comment by PLK2** [comment]
Screen Shot 2022-01-21 at 1 05 06 PM

**Comment by PLK2** [comment]
Screen Shot 2022-01-21 at 1 05 57 PM

**Comment by VajraOfIndra** [comment]
> I'm not seeing "Fetch upstream". See screenshot. That option appears if I Fork the repository, though... 

Yes, but you must have already forked the repository to work on the guide, right? You need to "Fetch upstream" from the forked branch in your repo that you have been working on. Does GitHub allow you to fetch the new commits or does it mention there are some conflicts?

**Comment by VajraOfIndra** [comment]
@PLK2 Are you still interested to work on this pull request? 

Right now it's very hard to see what are your changes as you've used an old branch. It'd be great if you could create a new branch based on an updated master branch in your repo and add your modification there and create a PR based on this modified branch (if you see what I mean). Like this, we could quickly review your modifications and be able to merge it easily.

Else, if you don't plant to work on this PR anymore, could you maybe close it?

**Pull request closed without merging**
