### PR TITLE
[UPDATE] Operating system guide update due to the Raspberry Pi Imager's latest versions changes

### PR DESCRIPTION
**Pull request by twofaktor**
#### What

Due to the latest interface [changes](https://github.com/raspberrypi/rpi-imager/releases) of the Rasberry Pi Imager v1.8+, the instructions to flash the Rasberry Pi OS on the Raspberry Pi and "enable booting from USB" have changed

### Why

Keep the guide updated

#### How

- Changed instructions to navigate across the tool
- Added a GIF that explains how to follow the steps
- Added new steps & deleted deprecated steps
- Deleted deprecated images
- Deleted deprecated URL and references to the version before

#### Scope

- [X] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Tested for me and working fine ✅

### CODE REVIEW

**Comment by hellresistor** [comment]
friend, Debian 12 from that link is good. i am using. if you want add
https://raspi.debian.net/tested-images/

**Comment by twofaktor** [comment]
> friend, Debian 12 from that link is good. i am using. if you want add https://raspi.debian.net/tested-images/

What do you mean? We haven't migrated RaspiBolt to the Bookworm version yet...

**Comment by hellresistor** [comment]
> > friend, Debian 12 from that link is good. i am using. if you want add https://raspi.debian.net/tested-images/
> 
> What do you mean? We haven't migrated RaspiBolt to the Bookworm version yet...

I mean I am using Debian 12 Bookworm RPI4 4GB and Raspibolt( https://raspi.debian.net/tested/20231109_raspi_4_bookworm.img.xz ). if you need, open a branch for bookworm i can test/help

**Comment by twofaktor** [comment]
> > > friend, Debian 12 from that link is good. i am using. if you want add https://raspi.debian.net/tested-images/
> > 
> > What do you mean? We haven't migrated RaspiBolt to the Bookworm version yet...
> 
> I mean I am using Debian 12 Bookworm RPI4 4GB and Raspibolt( https://raspi.debian.net/tested/20231109_raspi_4_bookworm.img.xz ). if you need, open a branch for bookworm i can test/help

Ok, thanks, Raspibolt will need to be fully tested using that new OS

**Comment by twofaktor** [comment]
could someone review this PR? @kristapsk @blckbx ?

**Review by blckbx — APPROVED** [review]
LGTM / utACK

**Review by Stadicus — APPROVED** [review]
Looks good! utACK.

**Pull request merged**
