### PR TITLE
[UPDATE BONUS GUIDE] Refresh and test for V3 of the BitBoxApp guide 

### PR DESCRIPTION
**Pull request by sutterseba**
#### What

* Refreshed the BitBoxApp guide by adding more detail specific to the RaspiBolt, especially in the Tor section. It still sticks to the [official guide by Shift Crypto](https://shiftcrypto.support/help/en-us/14-privacy/29-how-to-connect-the-bitboxapp-to-my-own-full-node) for the most part though.
* Changed status to _Tested V3_.
* Added two screenshots

#### Why

The BitBoxApp bonus guide was not tested for V3 yet and needed a refresh.

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Tested with BitBoxApp v.4.34.0 on macOS with both Tor Browser and Tor daemon.

If there are changes to the core Electrs guide (e.g. hidden service port number), the examples in this guide should be changed accordingly to avoid confusion.

### CODE REVIEW

**Comment by VajraOfIndra** [comment]
Thanks for updating/enhancing this guide 🙌 

That's one for @Stadicus  :)

**Review by blckbx — COMMENTED** [review]
LGTM

**Comment by sutterseba** [comment]
@Stadicus Can you take a quick look at this? 😀

**Comment by sutterseba** [comment]
@blckbx @VajraOfIndra I think we can merge?

**Comment by blckbx** [comment]
LFG  🚀 - chief seems too busy

**Pull request merged**
