### PR TITLE
Add mission control permission to macaroons table

### PR DESCRIPTION
**Pull request by vindard**
## Description

I added the permissions allowed/denied for the two mission control functions (`querymc` and `resetmc`) to the macaroons permissions table.

### CODE REVIEW

**Comment by Stadicus** [comment]
Is there a reference you could link, or another way to check?

**Comment by VajraOfIndra** [comment]
> I added the permissions allowed/denied for the two mission control functions (`querymc` and `resetmc`) to the macaroons permissions table.

Thanks, LGTM. How did you find out what commands each macaroon type contain? is there a reference list maintained by LND somewhere (couldn't find one so far) or is it by testing it manually?

utACK

@Stadicus are you ok to merge this PR even if untested or without a source?

**Review by VajraOfIndra — APPROVED** [review]
utACK, but the permissions look logical...

**Review by Stadicus — APPROVED** [review]

**Comment by VajraOfIndra** [comment]
Thanks a lot for your contribution @vindard ! We're merging your PR to master now :)

**Pull request merged**
