### PR TITLE
Fix UPS-Nut guide path & code formatting

### PR DESCRIPTION
**Pull request by VajraOfIndra**
#### What

- Fixes the wrong guide path
- Formatting of the code blocks for standardization with rest of the guide

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple bug fix

#### Test & maintenance

Check path is correct & new code formatting is ok

#### Animated GIF (optional)

wrong path

### CODE REVIEW

**Review by Stadicus — APPROVED** [review]
utACK, LGMT

**Comment by twofaktor** [comment]
Where appear this bonus guide in the Raspibolt guide? I can't find the link. Are included in the index.md of the bonus guide?

**Comment by VajraOfIndra** [comment]
> Where appear this bonus guide in the Raspibolt guide? I can't find the link. Are included in the index.md of the bonus guide?

It's missing indeed. I created a PR to add it, https://github.com/raspibolt/raspibolt/pull/1078, could you please leave a review?

**Comment by twofaktor** [comment]
> > Where appear this bonus guide in the Raspibolt guide? I can't find the link. Are included in the index.md of the bonus guide?
> 
> It's missing indeed. I created a PR to add it, #1078, could you please leave a review?

Review of this PR or this #1078?

**Comment by VajraOfIndra** [comment]
> > > Where appear this bonus guide in the Raspibolt guide? I can't find the link. Are included in the index.md of the bonus guide?
> > 
> > 
> > It's missing indeed. I created a PR to add it, #1078, could you please leave a review?
> 
> Review of this PR or this #1078?

This PR is already merged, I meant review of the new #1078 yes 👍 

> BTW: I'm not a "collaborator" only a "contributor", can I leave a review anyway?

Maintainer you mean? yes, you can absolutely leave a review, you just can't merge PRs into master

**Comment by twofaktor** [comment]
> > > > Where appear this bonus guide in the Raspibolt guide? I can't find the link. Are included in the index.md of the bonus guide?
> > > 
> > > 
> > > It's missing indeed. I created a PR to add it, #1078, could you please leave a review?
> > 
> > 
> > Review of this PR or this #1078?
> 
> This PR is already merged, I meant review of the new #1078 yes +1
> 
> > BTW: I'm not a "collaborator" only a "contributor", can I leave a review anyway?
> 
> Maintainer you mean? yes, you can absolutely leave a review, you just can't merge PRs into master

I left a review! did I do that fine? 🤓

https://github.com/raspibolt/raspibolt/pull/1078#pullrequestreview-1090006934

**Comment by VajraOfIndra** [comment]
> > > > > Where appear this bonus guide in the Raspibolt guide? I can't find the link. Are included in the index.md of the bonus guide?
> > > > 
> > > > 
> > > > It's missing indeed. I created a PR to add it, #1078, could you please leave a review?
> > > 
> > > 
> > > Review of this PR or this #1078?
> > 
> > 
> > This PR is already merged, I meant review of the new #1078 yes +1
> > > BTW: I'm not a "collaborator" only a "contributor", can I leave a review anyway?
> > 
> > 
> > Maintainer you mean? yes, you can absolutely leave a review, you just can't merge PRs into master
> 
> I left a review! did I do that fine? nerd_face


Yes, thats great! it actually helps a lot to quicken the review/approval process for the maintainers. :100:

**Pull request merged**
