### PR TITLE
Update lntop.md fix uninstall

### PR DESCRIPTION
**Pull request by HappyBear-btc**
#### What

current command does not remove lntop

### Why

sudo is missing

#### How

How was this change accomplished?

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [x] simple bug fix

Fixes # (link issue)

#### Test & maintenance

How can the changes be tested? Is there ongoing maintenance effort? If this is a bonus guide: are you willing to update it from time to time?

#### Animated GIF (optional)

Add some snazz if you feel like it :)

### CODE REVIEW

**Comment by kristapsk** [comment]
> current command does not remove .lntop folder

You meant "current command does not remove lntop executable".

**Review by kristapsk — APPROVED** [review]
ACK d3d72b81cb77c76d818cc3dbda9611e448b20edb

**Comment by HappyBear-btc** [comment]
o.k thank you. I changed it to just "doesn't remove lntop"

**Review by Mynima — APPROVED** [review]
utACK

**Pull request merged**
