### PR TITLE
[NEW BONUS GUIDE] Using REST Access (LAN)

### PR DESCRIPTION
**Pull request by Mynima**
#### What

Reviewed, updated, formalised and tested the REST Access (LAN) guide based on the earlier version provided by Rob Clark.

### Why

Figured it would be good to bring it 'in-house' so that in future it can be maintained along with other RaspiBolt Guides. Also forms the foundation of then including the WAN equivalent guide.

#### How

Reviewed original guide, made a few tweaks and formatted in line with other bonus guides.

#### Scope

- [ ] significant change to core configuration
- [x] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Can be retested/maintained along with other bonus guides (by the community) during future upgrades of LND.

#### Animated GIF (optional)

n/a

### CODE REVIEW

**Comment by twofaktor** [comment]
Could you remove the `bitcoin-client.md` mod and just leave the new bonus guide?

**Comment by Mynima** [comment]
> Could you remove the `bitcoin-client.md` mod and just leave the new bonus guide?

Reverted.

**Comment by twofaktor** [comment]
> > Could you remove the `bitcoin-client.md` mod and just leave the new bonus guide?
> 
> Reverted.

We have an existing PR #1191 with a bitcoin-client.md update, delete all bitcoin-client.md modifications, please

**Comment by Mynima** [comment]
> > > Could you remove the `bitcoin-client.md` mod and just leave the new bonus guide?
> > 
> > 
> > Reverted.
> 
> We have an existing PR #1191 with a bitcoin-client.md update, delete all bitcoin-client.md modifications, please

Sorry about that, I've corrected the outstanding differences and confirmed it is just the one file (with the bonus guide) included now in this PR.

**Comment by Mynima** [comment]
More important stuff being worked on. May revive this in the future

**Pull request closed without merging**
