### PR TITLE
[UPDATE GUIDE] Update LND (versioning)

### PR DESCRIPTION
**Pull request by Mynima**
#### What

Updating LND guide to v0.16.4

### Why

new version available with bug fix ([release notes](https://github.com/lightningnetwork/lnd/releases))

#### How

Reivew/update main guide.

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple bug fix

Fixes # (link issue)

#### Test & maintenance

Tested by upgrading.

Update identified via GitLurker https://www.gitlurker.info/

### CODE REVIEW

**Comment by twofaktor** [comment]
Line --> https://github.com/raspibolt/raspibolt/pull/1308/files#diff-95d7ff179bd7432b5299766d1f891af329103c5641c0d0d3a095f9891698fa11L86

Change to: 
`Success! Bitcoin block 797397 attests existence as of 2023-07-06 CEST`

**Comment by Mynima** [comment]
> Line --> https://github.com/raspibolt/raspibolt/pull/1308/files#diff-95d7ff179bd7432b5299766d1f891af329103c5641c0d0d3a095f9891698fa11L86
> 
> Change to: `> Success! Bitcoin block 797397 attests existence as of 2023-07-06 CEST`

Thanks, updated.

**Review by blckbx — APPROVED** [review]
LGTM :rocket:

**Review by twofaktor — APPROVED** [review]
utACK! tested on amd64! ✔️

**Pull request merged**
