### PR TITLE
System overview: 

### LINKED ISSUE #979: [BUG] After installing Lightning Terminal, the lnd version display is no longer correct.
### Describe the bug
After installing Lightning Terminal, the lnd version display is no longer correct.

### Location in guide
https://github.com/raspibolt/raspibolt/blob/master/resources/20-raspibolt-welcome

### Screenshots
admin@raspibolt:~ $ lncli -version
lncli version 0.14.2-beta commit=lightning-terminal-v0.6.5-alpha

The script "Bonus guide: System overview " uses this command to determine the lnd version and now requests an update of the lnd:

.. .. ฿itcoin (mainnet) up Lightning (LND) up
'. \ ' ' / .' v22.0.0 lightning-terminal-v0.6.5-alpha Update!

### Environment
Raspberry Pi 4
Raspberry Pi OS 64bit
2022-04-07_LI

### PR DESCRIPTION
**Pull request by mktech-gh**
#### What

Solution of issue #979

### Why

It's nice if the correct LND version is displayed on the welcome screen.

#### How

I query the currently installed LND version with the command "lncli getinfo" instead of the command "lncli -version".

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [ X] simple bug fix

Fixes #979  (link issue)

#### Test & maintenance

As user admin:
$ raspibold

#### Animated GIF (optional)

My first pull request :-)

### CODE REVIEW

**Review by VajraOfIndra — APPROVED** [review]
tACK, works like a charm!

**Comment by VajraOfIndra** [comment]
> Solution of issue #979.

Thanks a lot for fixing this bug @mktech-gh 

> My first pull request :-)

welcome to the contributor team! :tada: :)

**Comment by VajraOfIndra** [comment]
PS: FYI, you can use keywords to close an issue once your PR is merged. For example, in the opening comment you could write "Fixes #979" and when the PR is merged it will also close this Issue. It's quite handy.

The list of keywords that can be used is here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=

**Comment by mktech-gh** [comment]
@VajraOfIndra Thanks for your tips. That way I can keep improving 👍

**Pull request merged**
