### PR TITLE
Update LND to v0.15.2 (URGENT - hot fix)

### PR DESCRIPTION
**Pull request by VajraOfIndra**
#### What

* Update LND guide to [v0.15.2](https://github.com/lightningnetwork/lnd/releases/tag/v0.15.2-beta), an emergency hot fix for a [bug](https://github.com/lightningnetwork/lnd/issues/7002) that cause lnd nodes to be unable to parse certain large blocks.

Not upgrading can lead to loss of funds.

### Why

* Urgent bug fix.

#### Scope

- [ ] significant change to core configuration
- [x] minor change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

* Check that all occurences of version number has been updated
* Test the update and that LND is sync to chain:
> $ lncli getinfo | grep synced_to_chain
> > "synced_to_chain": true,

### CODE REVIEW

**Review by twofaktor — APPROVED** [review]
LGTM! 👍

**Review by blckbx — APPROVED** [review]
LGTM

**Review by Bitcoinite — APPROVED** [review]
LGTM

**Review by sig-noi — APPROVED** [review]
looks good to me! 
wish my lnd hadn't broken (maybe corrupted macaroon files) when I did the update but I think that was either user error or coincidental. In either case not an issue with the installation guide as well as I can tell.

**Review by kristapsk — APPROVED** [review]
ACK. Successfully upgraded my instance.

**Comment by kristapsk** [comment]
It looks there is bug in LND v0.15.1 regarding opening new channels to CLN nodes. My suggestion is to skip upgrade to v0.15.1 and wait for v0.15.2 (there is already fix merged into master). https://github.com/lightningnetwork/lnd/issues/6882

**Comment by twofaktor** [comment]
> It looks there is bug in LND v0.15.1 regarding opening new channels to CLN nodes. My suggestion is to skip upgrade to v0.15.1 and wait for v0.15.2 (there is already fix merged into master). [lightningnetwork/lnd#6882](https://github.com/lightningnetwork/lnd/issues/6882)

I agree with you, we should wait 🧐

**Pull request merged**
