### PR TITLE
Harmonize left menu headings with generic names

### LINKED ISSUE #930: [DISCUSSION]: Standardization of Bitcoin and Lightning sub-headings: generic names vs program names
## Introduction

As stated by @Stadicus in this [comment](https://github.com/raspibolt/raspibolt/pull/921#issuecomment-1044668250), it is preferrable to have generic names for the left menu headings:

> Regarding "Generic" vs. "Application-specific" titles: I strongly prefer the generic titles, at least when there's a choice. This also affects the filenames, and we can replace individual applications in the core guide easier if necessary.

It does indeed make the guide more future-proof. However, presently, there are still a couple of headings that derive their names from the chosen program to install on the node, namely:
* Bitcoin Core
* LND
* Ride The Lightning

NB: Interestingly I assume "Electrum server" has now become a generic name! E.g. Fulcrum could be categorized as an Electrum server, correct? I looked around to see if there was a more generic name without the term 'Electrum' in it but coulnd't find anything at all. Any thoughts on this? Feel freet to bring this in the discussion below and propose alternative names.

NB 2: In this post, I'll focus on the "Bitcoin" and "Lightning" chapters and will ignore the "Raspberry Pi" chapter of the guide, although the heading "Raspberry Pi" is more specific than generic... Feel freet to bring this in the discussion if you wish so.

---

## New names proposals

I propose below a few ideas to homogenize the left menu headings with the following goals:
* *Generic rather than specific*: All headings are have generic names and not program names
* *Industry standard*: The generic name are well-known and accepted categories in the bitcoin community
* *Short*: The names are kept short for ease of display and navigation

### Program: Bitcoin Core

* _Existing_: **Bitcoin Core**
* _Proposed_:  **Bitcoin Node**
* _Alternative_: **Bitcoin Node Implementation** -> Quite long (also not an implementation per se as there is no specifications, correct?.. but that's pedantry now :)
* Alternative: **Bitcoin Client** -> but it's more than just a client...
* Alternative: **Bitcoin Core** -> we keep it as is, see [comment](https://github.com/raspibolt/raspibolt/pull/921#issuecomment-1044668250). IMHO, I don't think it's needed to keep the program name as the generic names above looks suitable.

### Program: Electrs

* _Existing_: **Electrum server** -> 
* _Proposed_: **Electrum Server** -> Keep existing name. Unless someone can come up with a more generic name that does not use the term 'Electrum', if that even exists.

### Program: BTC RPC Explorer

* _Existing_: **Blockchain Explorer** 
* _Proposed_: **Blockchain Explorer** -> Keep existing name.

### Program: LND

* _Existing_:  **LND**
* _Proposed_: **LN Node** -> Reuse the same terminology as 'Bitcoin Node' = visually consistent
* _Alternative_: **LN Node Implementation** -> Technically better, but quite long

### Program: Ride The Lightning

* _Existing_: **Ride The Lightning**
* _Proposed_: **Web Node Manager** -> The RTL repo describes itself as "a full function, device agnostic, web user interface to help manage lightning node operations", while ThuderHub has "an open-source LND node manager where you can manage and monitor your node on any device or browser"
* _Alternative_: **Web Dashboard** -> A bit simpler and shorter than the above... but nor RTL or TH use the term dashboard

### Program: Zeus

* _Existing (soon! with Zeus)_: **Mobile Wallet** -> not ideal as Zeus is much more than just a LN wallet
* _Proposed_: **Mobile Node Manager** -> to reuse the terminology used for RTL
* _Alternative_: **Mobile Dashboard** -> idem but with dashboard which is simpler/shorter

I'll update the OP with any comments, pros/cons, and new name proposals made in the comments below!
I'll add new sections if you want to discuss other names not listed just above (Electrum server, Raspberry Pi or something else).

Wdyat?

### PR DESCRIPTION
**Pull request by VajraOfIndra**
#### What

See discussion in #930 

_tl;dr_: The PR updates the left menu headings to make them generic rather than program-specific.

### Why

* Consistency/harmonization
* Makes it easier to switch a program with another one in the future if desired, without changing the guide's main structure

#### How

* Changed file names: `*.md`
* Changed yml titles
* Changed h1 titles
* Changed the title/path of the "Next" links at the bottom of the page

#### Scope

- [x] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

Fixes #930 

#### Test & maintenance

Make sure there is no broken links and that all relevant files have been updated with the proper name.

names

### CODE REVIEW

**Comment by Stadicus** [comment]
Looking good! I ran the branch through a broken link checker and fixed quite a few (new and old) issues with internal links.



You can find my fix here: https://github.com/Stadicus/raspibolt-dev/commit/711059cb6f32f6e1dc91244668f0b405362b1751

I tried to push my commit directly to your branch (which [should be possible](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork) if you enabled "Allow edits from maintainers"), but that didn't work. 

image

[Could you check](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) if this setting is enabled?

**Comment by VajraOfIndra** [comment]
> Looking good! I ran the branch through a broken link checker and fixed quite a few (new and old) issues with internal links.

Wow, this website looks really useful, bookmarked!
 
> [Could you check](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) if this setting is enabled?

On the PR page, the 'Allow..' box is ticked:
image

Any other ideas what could cause the restriction?

**Comment by Stadicus** [comment]
> Any other ideas what could cause the restriction?

Not really. We can merge this PR into a development branch (e.g. `raspibolt/generic-names`), I'll add my commit there, and then we merge it into `master`.

I changed this pull-request accordingly. I think that's a good way to go also for future change requests, if someone starts a change on their own, and then others want to contribute.

**Review by Stadicus — APPROVED** [review]
LGTM, with some fixes of broken links being added in the target developent branch `generic-names` by Stadicus afterwards

**Comment by VajraOfIndra** [comment]
> > Any other ideas what could cause the restriction?
> 
> Not really. We can merge this PR into a development branch (e.g. `raspibolt/generic-names`), I'll add my commit there, and then we merge it into `master`.
> 
> I changed this pull-request accordingly.


Good idea! Just merged this PR into `raspibolt:generic-names`.

**Pull request merged**
