### PR TITLE
Several improvements to Raspibolt general guide (enable i2p network BTC Core + filters + Lightning + bonus guides, ...)

### PR DESCRIPTION
**Pull request by twofaktor**
#### What

- Install and enable i2p daemon in privacy section
- Important improvements in BTC Core network, enabling i2p network
- Enable all filters in BTC Core to improve compatibility with differents wallets. Exclusive activation of bloomfilters for Bisq
- Add Tor and ip2 logs to ensure the both networks are working fine (only this will appear at the logs of starting process of Core)
- Add privacy mode of BTC Core and tor + i2p seed nodes to ensure discover peers
- Update BTC RPC Explorer guide to include Fulcrum API connection + DEMO mode to share the private explorer with confidence people
- Update aliases bonus guide (more clarif for future modifications)
- Fix and update Bisq bonus guide
- Clarified Thunderhub bonus guide

### Why

This can lead to significant improvements to the Raspibolt nodes.

#### How

Adding what is needed to install and enable. This affects both privacy, bitcoin-client and btc rpc explorer sections

#### Scope

- [x] significant change to core configuration
- [x] independent bonus guide
- [x] simple bug fix

#### Test & maintenance

I tested all and is working fine for me:

`bitcoin-cli -netinfo`

```
Bitcoin Core client v23.0.0 - server 70016/Satoshi:23.0.0/

         ipv4    ipv6   onion     i2p   total   block
in          0       0      25       2      27
out         7       0       2       1      10       2
total       7       0      27       3      37

```

### CODE REVIEW

**Review by twofaktor — COMMENTED** [review]
- install, activate and monitoring i2p network
- Activate general filters (for Bisq and wallets compatibility)
- Open connections for Bisq local network
- Add whitelist for bisq connection
- Add privacy mode for BTC Core / add Tor and i2p seednodes

**Comment by Stadicus** [comment]
Great additions, but I think it's a bit much for one pull request. In particular:

* There should be a dedicated pull request per topic or bonus guide
* For now, I would prefer if i2p should be its own bonus guide and not part of the core guide
* The main guide users Electrs, and we should not add configurations for Fulcrum here. All changes required to use Fulcrum instead of Electrs should be part of the Fulcrum bonus guide.
* Changes required for Bisq should be part of the Bisq bonus guide.

Also, I'm not sure if serving compact block filters and other changes have downsides, e.g., increasing the attack vector for DoS attacks, or using more upload data bandwidth. What's the reasoning behind this? Could support for BIP157 be its own bonus guide?

It would be great if you could split these changes into smaller pull requests so that each topic can be discussed and reviewed individually.

**Comment by twofaktor** [comment]
> Great additions, but I think it's a bit much for one pull request. In particular:
> 
> * There should be a dedicated pull request per topic or bonus guide
> * For now, I would prefer if i2p should be its own bonus guide and not part of the core guide
> * The main guide users Electrs, and we should not add configurations for Fulcrum here. All changes required to use Fulcrum instead of Electrs should be part of the Fulcrum bonus guide.
> * Changes required for Bisq should be part of the Bisq bonus guide.
> 
> Also, I'm not sure if serving compact block filters and other changes have downsides, e.g., increasing the attack vector for DoS attacks, or using more upload data bandwidth. What's the reasoning behind this? Could support for BIP157 be its own bonus guide?
> 
> It would be great if you could split these changes into smaller pull requests so that each topic can be discussed and reviewed individually.

Thanks for you review! How I can create simultaneously pull requests of differents sections and separe it?

**Comment by kristapsk** [comment]
Also agree with @Stadicus that this should be split into multiple pull requests, so that each can be reviewed separately.

**Comment by kristapsk** [comment]
> Thanks for you review! How I can create simultaneously pull requests of differents sections and separe it? i think is not possible to do this simultaneously with the same account user

You can, need to do separate git brach for each PR. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches

**Comment by twofaktor** [comment]
Ok, I will to do separate brach for each PR and to make the proposals. I close this PR

**Comment by Stadicus** [comment]
Thanks! :pray:

**Pull request closed without merging**
