### PR TITLE
Instructions to add CLN REST over Tor and CLN QR code generation for Zeus

### PR DESCRIPTION
**Pull request by s373nZ**
#### What

Adding additional information on how to expose CLN REST over Tor and generate a QR code for Zeus node configuration.

### Why

These change exist in the documentation for LND, but it is left largely to the user to figure out how to fill the gaps if they choose to run a CLN node.

#### How

Copied proces from LND documentation and help on QR code generation here:

https://github.com/ZeusLN/zeus/issues/515

along with linked Twitter post and some help from `elkaladiente` in Rapibolt Telegram channel.

#### Scope

- [ ] significant change to core configuration
- [x ] independent bonus guide
- [ ] simple bug fix

Fixes # (link issue)

#### Test & maintenance

How can the changes be tested? Is there ongoing maintenance effort? If this is a bonus guide: are you willing to update it from time to time?

Test by trying to connect Zeus application to CLN with QR code over Tor.

#### Animated GIF (optional)

Add some snazz if you feel like it :)

### CODE REVIEW

**Comment by blckbx** [comment]
> good contribution!!
> 
> But we have Zeus as the main mobile app for Lightning: https://github.com/raspibolt/raspibolt/blob/master/guide/lightning/mobile-app.md https://raspibolt.org/guide/lightning/mobile-app.html
> 
> Should we add this there instead of in the CLN guide? wdyt?

Good addon @s373nZ!

I guess I started this trend by configuring RTL - which we also already have as default web-app in LND - to work with CLN in the initial guide. This PR basically adds to the style.

The more general question in the room is if we want to add separate bonus guides for CLN, so this guide doesn't get too clumsy to use if we continue to add more stuff for CLN like e.g. plugins etc. In the end it's probably a good idea to have a special CLN section in Bonus -> Lightning.

**Comment by s373nZ** [comment]
Thanks :)

@twofaktor - This wasn't meant as a replacement for the existing Zeus documentation at all. I just wanted to add the pieces I was missing to get CLN up and running through Tor and connected to the mobile app when following the CLN bonus guide *instead* of using LND.

@blckbx - Agreed - if you want to rethink the bonus guide organization around CLN, that's another story. And up to you guys...

**Comment by blckbx** [comment]
> @blckbx - Agreed - if you want to rethink the bonus guide organization around CLN, that's another story. And up to you guys...

Yes, let's do this after merging. 

I successfully tested this PR. Although one question: Instead of additionally installing `qrencode`, I was able to use `qr` which comes preinstalled on Ubuntu LTS and Umbrel-OS. Not sure if it also comes with Raspi-OS.

I just ran: `cat cln-qr-code-template | qr` , scanned the QR code and connected with Zeus.
So could we simply make use of this built-in command?

**Comment by s373nZ** [comment]
@blckbx I built a new Raspibolt a few weeks ago and I just logged in to check - `qr` is not available out of the box for me on Debian 11. I used the instructions in Raspberry Pi > Operating System to set up.

**Comment by blckbx** [comment]
> @blckbx I built a new Raspibolt a few weeks ago and I just logged in to check - `qr` is not available out of the box for me on Debian 11. I used the instructions in Raspberry Pi > Operating System to set up.

Thanks for checking! Must've been some special python lib. 
Anyway I take it all back and tACK your approach.

**Review by blckbx — APPROVED** [review]
🚀

**Pull request merged**
