### PR TITLE
[UPDATE] Bump LND to v0.17.3

### PR DESCRIPTION
**Pull request by twofaktor**
#### What

Updates LND guide to newly released v0.17.3

### Why

Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/v0.17.3-beta/docs/release-notes/release-notes-0.17.3.md))

#### How

- Updated variable environment and outputs

#### Scope

- [x] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Tested for myself. Working fine ✅

imagen

### CODE REVIEW

**Comment by blckbx** [comment]
tACK amd64

**Comment by kristapsk** [comment]
Why are we hurrying so fast with merges? This doesn't look so critical. It's better to let more people review too, just in case.

**Review by kristapsk — COMMENTED** [review]
post-merge ACK

**Comment by twofaktor** [comment]
> Why are we hurrying so fast with merges? This doesn't look so critical. It's better to let more people review too, just in case.

Why is this different for you? https://github.com/raspibolt/raspibolt/pull/1366#pullrequestreview-1687850813

I'm not a fan of the utACK, btw

**Comment by kristapsk** [comment]
> > Why are we hurrying so fast with merges? This doesn't look so critical. It's better to let more people review too, just in case.
> 
> Why is this different for you? [#1366 (review)](https://github.com/raspibolt/raspibolt/pull/1366#pullrequestreview-1687850813)
> 
> I'm not a fan of the utACK, btw

Configuration / documentation change is more easy to rollback than software update in case something goes wrong. It just gave hint what to do in case of specific error, didn't change core software or even core config.

**Pull request merged**
