### PR TITLE
Monitoring channel.db size in welcome/motd script

### PR DESCRIPTION
**Pull request by VajraOfIndra**
#### What

This pull-request adds a few lines to the `20-raspibolt-welcome` script to display the `channel.db` size in the LND section of the 'message of the day' (motd) system overview. (See previous version of the PR with comments [here](https://github.com/raspibolt/raspibolt/pull/776))

### Why

When `channel.db` reaches ~1GB on 32-bit OS, LND experienced issues (e.g. [here](https://github.com/lightningnetwork/lnd/issues/4811){:target="_blank"}). Issues can also be met on 64-bit OSes when reaching larger sizes on low-spec devices (e.g. [here](https://github.com/lightningnetwork/lnd/issues/5705){:target="_blank"}). Therefore, monitoring the growth of the channel.db size is critical.

#### How

The `channel.db` size is obtained in the script using the following command (but see section below for possible improvements):
`du -h /mnt/ext/lnd/data/graph/mainnet/channel.db | awk '{print $1}'`

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] minor change to bonus guide
- [ ] simple bug fix

#### Test & maintenance

* How can the changes be tested?
  * The change can be tested by running the modified script on the node. The new line should appear in system overview message in the terminal.
* Is there ongoing maintenance effort? 
  * There is no ongoing maintenance effort, this is a one-off change that should remain valid for the foreseeable future.
* If this is a bonus guide: are you willing to update it from time to time?
  * N/A, see above

#### Ideas for future improvements

For now the variable is a string. Getting an integer instead would allow to create a simple conditional statement to colour-code the line in green, orange and red when below or above a certain size (e.g. <500MB green, 500-900MB orange, >900MB red)

#### Animated GIF (optional)

db

### CODE REVIEW

**Comment by Stadicus** [comment]
The Channel.db size is shown correctly. :heavy_check_mark: 

Overall, I can't really check this welcome script as it's not yet compatible with the RaspiBolt v3.

I get the following error messages, because user "bitcoin" can't access `lncli` and `netcat` is not yet installed:

```sh
sudo raspibolt
timeout: failed to run command 'nc': No such file or directory
[lncli] could not load global options: could not load TLS cert file: open /home/bitcoin/.lnd/tls.cert: no such file or directory
[lncli] could not load global options: could not load TLS cert file: open /home/bitcoin/.lnd/tls.cert: no such file or directory
[lncli] could not load global options: could not load TLS cert file: open /home/bitcoin/.lnd/tls.cert: no such file or directory
/usr/local/bin/raspibolt: 338: netcat: not found
```

Here's how the welcome screen output looks:

image

If you can test this simple change, that's fine, then let's merge it. I can then fix the rest of the script to update it to v3. WDYT?

**Review by Stadicus — APPROVED** [review]
This change is simple enough and works as intended. An upgrade to RaspiBolt v3 is out-of-scope for this pull request.

I'll merge this change into the `welcome-script-staging` branch and update it to version 3 before merging it into master.

To stay compatible with v2: we need to consider how to link `/data` to `/mnt/ext`

**Comment by Stadicus** [comment]
GitHub markdown tip: No need to create links when linking to issues or pull requests. And the `{:target="_blank"}` only works with the Just The Docs template.

You can simply link to an issue by pasting the full URL, GitHub will take care of the rest. 

```
Example:  https://github.com/lightningnetwork/lnd/issues/5705
```

Example:  https://github.com/lightningnetwork/lnd/issues/5705

**Comment by VajraOfIndra** [comment]
> Overall, I can't really check this welcome script as it's not yet compatible with the RaspiBolt v3.
> 
> I get the following error messages, because user "bitcoin" can't access `lncli` and `netcat` is not yet installed:
> 
> ```shell
> sudo raspibolt
> timeout: failed to run command 'nc': No such file or directory
> [lncli] could not load global options: could not load TLS cert file: open /home/bitcoin/.lnd/tls.cert: no such file or directory
> [lncli] could not load global options: could not load TLS cert file: open /home/bitcoin/.lnd/tls.cert: no such file or directory
> [lncli] could not load global options: could not load TLS cert file: open /home/bitcoin/.lnd/tls.cert: no such file or directory
> /usr/local/bin/raspibolt: 338: netcat: not found
> ```

Ah yes, I should have thought about this. I'm still on v2 (I almost had my v3 ready but have to start again from scratch... long story) so didn't test it on v3 and forgot that some stuff would be broken, good catch!

**Comment by VajraOfIndra** [comment]
> This change is simple enough and works as intended. An upgrade to RaspiBolt v3 is out-of-scope for this pull request.
> 
> I'll merge this change into the `welcome-script-staging` branch and update it to version 3 before merging it into master.

Ok, makes sense.

> To stay compatible with v2: we need to consider how to link `/data` to `/mnt/ext`

Just to tease it out and for me to learn: wouldn't the goal of staying compatible with v2 create some sort of burden on v3 that could complicate future improvements? (I'm thinking not only this issue above but in general, long-term). Is there a real need for the guide to stay compatible with previous versions? Just curious to hear your thoughts on this :)

**Comment by VajraOfIndra** [comment]
> GitHub markdown tip: No need to create links when linking to issues or pull requests. And the `{:target="_blank"}` only works with the Just The Docs template.

Great to know, thanks!

**Pull request merged**
