### PR TITLE
[UPDATE GUIDE] Update RTL v0.15.0

### PR DESCRIPTION
**Pull request by blckbx**
### What

Updating RTL to v0.15.0 supports `clnrest` interface for CLN (#1392)
 
### How

Following instructions on https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.15.0

### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple app update

### CODE REVIEW

**Comment by kristapsk** [comment]
I think this doesn't address this new requirement:

> NodeJS version 0.18 or higher

**Comment by blckbx** [comment]
> I think this doesn't address this new requirement:
> 
> > NodeJS version 0.18 or higher

```
$ NODE_MAJOR=20
```
The guide is already set to use latest Node version v20.

**Comment by kristapsk** [comment]
> > I think this doesn't address this new requirement:
> > > NodeJS version 0.18 or higher
> 
> ```
> $ NODE_MAJOR=20
> ```
> 
> The guide is already set to use latest Node version v20.

Ahh, ok.

**Review by kristapsk — APPROVED** [review]
ACK 5a2fc91f6939eadd31de6e754cb40f843f1c6abd

**Pull request merged**
