### PR TITLE
Replaces outdated LN+ watchtower address with the new one

### PR DESCRIPTION
**Pull request by VajraOfIndra**
#### What

Existing LN+ watchtower is outdated, see their announcement on their website (https://lightningnetwork.plus/watchtower):
image

The PR replaces the old address with the new recommended one (displayed furtther down the webpage: https://lightningnetwork.plus/watchtower

image

The issue was flagged here: https://t.me/raspibolt/11758

#### Scope

- [ ] significant change to core configuration
- [x] minor change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

#### Test & maintenance

Test the new watchtower

#### Animated GIF (optional)
WT

### CODE REVIEW

**Review by kristapsk — APPROVED** [review]
ACK 8f382a1edb70fdd4184ebe305d9fa925f9233798

**Review by mktech-gh — COMMENTED** [review]
Just copy/pasted it to my Raspbolt. The new watchtower is active.
I deleted the old watchtower with:
lncli wtclient remove 0301135932e89600b3582513c648d46213dc425c7666e3380faa7dbb51f7e6a3d6

**Comment by kristapsk** [comment]
I have problem removing old one, but guess just need to wait.
```
$ lncli wtclient remove 0301135932e89600b3582513c648d46213dc425c7666e3380faa7dbb51f7e6a3d6
[lncli] rpc error: code = Unknown desc = removing towers is disallowed while a new session negotiation is in progress
```

**Comment by VajraOfIndra** [comment]
> Just copy/pasted it to my Raspbolt. The new watchtower is active. I deleted the old watchtower with: lncli wtclient remove 0301135932e89600b3582513c648d46213dc425c7666e3380faa7dbb51f7e6a3d6

Thanks! I added a couple of comamnd lines to show the user how to list their towers and how to deactivate one.

**Review by Stadicus — APPROVED** [review]
LGTM! :)

**Pull request merged**
