### PR TITLE
Bump LND to v0.17 + added flag to enable simple taproot channels

### PR DESCRIPTION
**Pull request by twofaktor**
#### What

Updates LND guide to newly released v0.17.0

### Why

Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.17.0.md)).

#### How

- Updated variable environment and outputs
- Added flag to enable support to simple taproot channels (https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L1476-L1477) | Attention: for the moment, this feature will be enabled only to private channels until the gossip 1.5 update is done, using `lncli openchannel --channel_type=taproot` 

#### Scope

- [X] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

#### Additional context

https://lightning.engineering/posts/2023-10-03-lnd-0.17-launch/
https://github.com/lightningnetwork/lnd/releases/tag/v0.17.0-beta

### CODE REVIEW

**Review by blckbx — APPROVED** [review]
tACK amd64

**Comment by twofaktor** [comment]
Tested on arm64 + amd64, running without issues ✅

lnd0 17

**Comment by kristapsk** [comment]
> * Added flag to enable support to simple taproot channels (https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L1476-L1477) | Attention: for the moment, this feature will be enabled only to private channels until the gossip 1.5 update is done, using `lncli openchannel --channel_type=taproot`

Should we suggest people doing it by default right now? I'm not sure, as it is experimental feature, not tested enough.

**Comment by kristapsk** [comment]
> > > * Added flag to enable support to simple taproot channels (https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L1476-L1477) | Attention: for the moment, this feature will be enabled only to private channels until the gossip 1.5 update is done, using `lncli openchannel --channel_type=taproot`
> > 
> > 
> > Should we suggest people doing it by default right now? I'm not sure, as it is experimental feature, not tested enough.
> 
> I think there is a second step by using `lncli openchannel --channel_type=taproot` then a non-experienced user shouldn't know it. Also, we don't have the intention to add that command to the guide, for the moment, but I think we should already be ready to receive a channel of this type from other peers anyway

Ok, makes sense.

Will test with my node soon.

**Review by kristapsk — APPROVED** [review]
ACK 149c2ef9ac8985a14e9ac752c909a9e1c32b26a3

**Comment by twofaktor** [comment]
Ok! Thxs! Let's go to the main! 🚀

**Pull request merged**
