### PR TITLE
Update LND guide to v0.16.2

### PR DESCRIPTION
**Pull request by kristapsk**
#### What

Updates LND guide to newly released v0.16.2.

### Why

Keeping up with latest developments and improvements (see [release notes](https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.16.2.md)).

#### Scope

- [X] significant change to core configuration
- [ ] independent bonus guide
- [ ] simple bug fix

### CODE REVIEW

**Comment by Mynima** [comment]
Is it worth swapping it to use a VERSION variable assignment to be consistent with the way we're going with the other guides?

$ VERSION = "0.16.2-beta"
$ wget https://github.com/lightningnetwork/lnd/releases/download/v0.16.1-beta/lnd-linux-arm64-v$VERSIONa.tar.gz

etc..

**Comment by twofaktor** [comment]
> Is it worth swapping it to use a VERSION variable assignment to be consistent with the way we're going with the other guides?
> 
> $ VERSION = "0.16.2-beta"
> $ wget https://github.com/lightningnetwork/lnd/releases/download/v0.16.1-beta/lnd-linux-arm64-v$VERSIONa.tar.gz
> 
> etc..
> 

PR related abandoned:

https://github.com/raspibolt/raspibolt/pull/1200

**Review by blckbx — COMMENTED** [review]
Line 256 still shows old version number 0.16.0 (though log timestamps are old and don't match as well). So up to you if you wanna touch the log output.

**Comment by kristapsk** [comment]
> Is it worth swapping it to use a VERSION variable assignment to be consistent with the way we're going with the other guides?
> 
> $ VERSION = "0.16.2-beta" $ wget https://github.com/lightningnetwork/lnd/releases/download/v0.16.1-beta/lnd-linux-arm64-v$VERSIONa.tar.gz
> 
> etc..

Let's not mix different things in a single PR, that is out of the scope.

**Comment by kristapsk** [comment]
> Line 256 still shows old version number 0.16.0 (though log timestamps are old and don't match as well). So up to you if you wanna touch the log output.

Fixed in 6af4ad1b1a7bef2e33d6101abf9d85aca191d33a

**Review by blckbx — APPROVED** [review]
utACK

**Review by twofaktor — APPROVED** [review]
tACK! Let's go! 🚀

**Pull request merged**
