### PR TITLE
Next electrs release will use `log_filters` instead of `verbose` config

### PR DESCRIPTION
**Pull request by romanz**
Following https://github.com/romanz/electrs/pull/615.

### CODE REVIEW

**Comment by romanz** [comment]
(not sure if this is the correct repo/branch though...)

**Comment by Stadicus** [comment]
Thanks, that's just fine :)

IIUC, this setting will become relevant with version 0.9.3? I'm happy to merge it then, after updating the Electrs section to the new version.

**Comment by romanz** [comment]
> IIUC, this setting will become relevant with version 0.9.3?

Yes, it was implemented after 0.9.2 and will be probably released in the end of this month :)

**Comment by romanz** [comment]
0.9.3 was released yesterday -> https://github.com/romanz/electrs/pull/628

**Comment by bmml1** [comment]
I get an error in the log_filters line. When using double quotes it seems to work fine.

`Error: Failed to parse configuration file /mnt/ext/electrs/electrs.conf: invalid TOML value, did you mean to use a quoted string? at line 20 column 15
`

**Comment by romanz** [comment]
Thanks, good catch!
Fixed in https://github.com/raspibolt/raspibolt/commit/02d3d5f958d2d21e58029cb0343f7362a1b0ce8a.

**Comment by Stadicus** [comment]
Thanks for your contribution. This pull request was resolved with the update to RaspiBolt version 3.

**Pull request closed without merging**
