### PR TITLE
Electrs version bump (v0.9.9)

### PR DESCRIPTION
**Pull request by sutterseba**
#### What

Bumped electrs version numbers to v0.9.9

#### Scope

- [ ] significant change to core configuration
- [ ] independent bonus guide
- [x] simple bug fix

### CODE REVIEW

**Comment by twofaktor** [comment]
What are the new features of this release?

**Comment by VajraOfIndra** [comment]
> What are the new features of this release?

It looks like the devs didn't update the release notes yet: https://github.com/romanz/electrs/blob/master/RELEASE-NOTES.md
The last entry is for v0.9.8....

**Comment by twofaktor** [comment]
Yeah, it appear some dependencies updates and some bug fix of regtest network

I think we should wait a few days 

Also, there is an open issue, that could rethink us revert `index_lookup_limit` parameter of unlimited to limited parameter like e.g 200 to slow devices like Raspis:
 https://github.com/romanz/electrs/issues/681

Could someone try open this BTC address in your personal BTC RPC Explorer and tell me that what happen?

1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

**Comment by sutterseba** [comment]
Release notes for v0.9.9 have been updated.

Turns out they have been there the whole time, just with the wrong number. 🙃

**Comment by twofaktor** [comment]
could someone try open this BTC address in your personal BTC RPC Explorer with unlimited conf and tell me what happen?

1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

**Comment by twofaktor** [comment]
> Release notes for v0.9.9 have been updated.
> 
> Turns out they have been there the whole time, just with the wrong number. 🙃 

😐

 Update dependencies (anyhow, crossbeam-channel, crossbeam-utils, regex, serde, serde from , serde_json, signal-hook)

 Don't log scripthash (#737)

**Comment by VajraOfIndra** [comment]
> could someone try open this BTC address in your personal BTC RPC Explorer with a Electrs unlimited conf and tell me what happen?
> 
> 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

I tested it. The Explorer did display the results but it took a good full minute of working before it did.

**Review by VajraOfIndra — APPROVED** [review]
LGTM, tACK!

Let's go to master :tada:

**Pull request merged**
